#!/bin/bash
#
#$ -q std.q
#$ -cwd
#$ -o output_montecarlo_noprint
#$ -e error.dat
#$ -pe openmp 8

g++ AvlTree.cpp AvlTree.h AvlNode.cpp AvlNode.h AvlMain.cpp -std=c++11 -g -Wall -Wextra -O3 -march=native -fopenmp

export OMP_NUM_THREADS=8
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel

export OMP_NUM_THREADS=4
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel

export OMP_NUM_THREADS=2
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel

export OMP_NUM_THREADS=1
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel
./avltree 2000 parallel

export OMP_NUM_THREADS=1
./avltree 2000 
./avltree 2000
./avltree 2000 
./avltree 2000 
