#!/bin/bash
#
#$ -q std.q
#$ -cwd
#$ -o output_avltree
#$ -e error.dat
#$ -pe openmp 8

export OMP_NUM_THREADS=8
./avltree 10000 parallel
./avltree 20000 parallel
./avltree 40000 parallel
./avltree 80000 parallel

export OMP_NUM_THREADS=4
./avltree 10000 parallel
./avltree 20000 parallel
./avltree 40000 parallel
./avltree 80000 parallel

export OMP_NUM_THREADS=2
./avltree 10000 parallel
./avltree 20000 parallel
./avltree 40000 parallel
./avltree 80000 parallel

export OMP_NUM_THREADS=1
./avltree 10000 parallel
./avltree 20000 parallel
./avltree 40000 parallel
./avltree 80000 parallel

export OMP_NUM_THREADS=1
./avltree 10000
./avltree 20000
./avltree 40000
./avltree 80000
