#!/bin/bash
#
#$ -q std.q
#$ -cwd
#$ -o output_avltree_part
#$ -e error.dat
#$ -pe openmp 8

export OMP_NUM_THREADS=8
./avltree 10000 parallel
./avltree 20000 parallel
./avltree 40000 parallel

export OMP_NUM_THREADS=4
./avltree 20000 parallel

