#!/bin/bash

#$ -N mpi_test
#$ -q std.q
#$ -cwd
#$ -o output_fix
#$ -e output_error

# exclusively reserve whatever nodes this is running on
#$ -l excl=true

# reserve 4GB of memory per process
#$ -l h_vmem="4G"

#$ -pe openmpi-8perhost 4

module load gcc/8.2.0
module load openmpi/3.1.1

mpirun -np 4 ./mpi_test 10 2 510 2 -0.5 0.5 1.0 0

mpirun -np 4 ./mpi_test 100 2 766 2 -0.5 0.5 1.0 0

mpirun -np 4 ./mpi_test 100 2 1022 2 -0.5 0.5 1.0 0
