#!/bin/bash

#$ -N mpi_test
#$ -q std.q
#$ -cwd
#$ -o output_768
#$ -e error_768

# exclusively reserve whatever nodes this is running on
#$ -l excl=true

# reserve 4GB of memory per process
#$ -l h_vmem="4G"

#$ -pe openmpi-8perhost 64

module load gcc/8.2.0
module load openmpi/3.1.1

mpirun -np 1 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 2 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 4 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 8 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 16 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 32 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
mpirun -np 64 ./mpi_test 100 2 768 2 -0.5 0.5 1.0 0
