#!/bin/bash

#$ -N mmul
#$ -q std.q
#$ -cwd
#$ -o mmul_output
#$ -e mmul_error

# exclusively reserve whatever nodes this is running on
#$ -l excl=true

# reserve 4GB of memory per process
#$ -l h_vmem="4G"

#$ -pe openmpi-8perhost 64

module load gcc/8.2.0
module load openmpi/3.1.1

mpirun -np 1 ./mmul 3072

mpirun -np 2 ./mmul 3072

mpirun -np 4 ./mmul 3072

mpirun -np 8 ./mmul 3072

mpirun -np 16 ./mmul 3072

mpirun -np 32 ./mmul 3072

mpirun -np 64 ./mmul 3072
