#!/bin/bash
#
#$ -q std.q
#$ -cwd
#$ -o output_real
#$ -e error_real
#$ -pe openmp 8

module load gcc/8.2.0

time ./real
perf stat -e cycles,instructions,cache-references,cache-misses,bus-cycles,cpu-clock ./real
perf record -e cycles,instructions,cache-references,cache-misses,bus-cycles,cpu-clock ./real
perf report --stdio --sort comm,dso
perf report --stdio --dsos=real,libgomp.so.1.0.0,libc-2.17.so
perf annotate --stdio --dsos=real --symbol=resid
perf annotate --stdio --dsos=real --symbol=psinv
perf annotate --stdio --dsos=real --symbol=rprj3
perf annotate --stdio --dsos=real --symbol=interp
perf annotate --stdio --dsos=real --symbol=vranlc	

